## Deliverable 2. Create a Customer Travel Destinations Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config2 import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [2]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("weather_database/WeatherPy_database.csv")
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Date
0,0,Kaihua,CN,23.3687,104.2800,58.96,99,100,4.16,overcast clouds,2021-10-30 22:49:31
1,1,Ushuaia,AR,-54.8000,-68.3000,51.46,46,0,18.41,clear sky,2021-10-30 22:46:37
2,2,Luderitz,NaN,-26.6481,15.1594,58.48,93,9,3.00,clear sky,2021-10-30 22:49:32
3,3,Vila Franca Do Campo,PT,37.7167,-25.4333,74.19,93,100,14.43,overcast clouds,2021-10-30 22:49:32
4,4,Kapaa,US,22.0752,-159.3190,80.58,86,40,4.00,scattered clouds,2021-10-30 22:49:33

In [3]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [4]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                      (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Date
4,4,Kapaa,US,22.0752,-159.3190,80.58,86,40,4.00,scattered clouds,2021-10-30 22:49:33
10,10,Cabinda,AO,-5.5500,12.2000,77.56,86,91,8.52,light rain,2021-10-30 22:49:37
11,11,Hua Hin,TH,12.5707,99.9588,77.45,87,100,4.23,overcast clouds,2021-10-30 22:49:37
17,17,Rikitea,PF,-23.1203,-134.9692,75.13,85,84,21.00,light rain,2021-10-30 22:47:06
19,19,Georgetown,MY,5.4112,100.3354,78.73,92,40,5.99,scattered clouds,2021-10-30 22:45:10
20,20,Kapoeta,SS,4.7717,33.5903,81.82,42,96,5.53,overcast clouds,2021-10-30 22:49:42
25,25,Soyo,AO,-6.1349,12.3689,77.54,84,96,9.95,overcast clouds,2021-10-30 22:49:44
29,29,Puerto Escondido,MX,15.8500,-97.0667,82.60,77,83,3.24,broken clouds,2021-10-30 22:49:46
30,30,Bengkulu,ID,-3.8004,102.2655,76.01,90,100,5.53,overcast clouds,2021-10-30 22:49:47
34,34,Hilo,US,19.7297,-155.0900,82.13,72,40,8.05,scattered clouds,2021-10-30 22:47:31

In [5]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.count()

City_ID                200
City                   200
Country                198
Lat                    200
Lng                    200
Max Temp               200
Humidity               200
Cloudiness             200
Wind Speed             200
Current Description    200
Date                   200
dtype: int64

In [6]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
clean_pref_cities_df = preferred_cities_df.dropna()
clean_pref_cities_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Date
4,4,Kapaa,US,22.0752,-159.3190,80.58,86,40,4.00,scattered clouds,2021-10-30 22:49:33
10,10,Cabinda,AO,-5.5500,12.2000,77.56,86,91,8.52,light rain,2021-10-30 22:49:37
11,11,Hua Hin,TH,12.5707,99.9588,77.45,87,100,4.23,overcast clouds,2021-10-30 22:49:37
17,17,Rikitea,PF,-23.1203,-134.9692,75.13,85,84,21.00,light rain,2021-10-30 22:47:06
19,19,Georgetown,MY,5.4112,100.3354,78.73,92,40,5.99,scattered clouds,2021-10-30 22:45:10
20,20,Kapoeta,SS,4.7717,33.5903,81.82,42,96,5.53,overcast clouds,2021-10-30 22:49:42
25,25,Soyo,AO,-6.1349,12.3689,77.54,84,96,9.95,overcast clouds,2021-10-30 22:49:44
29,29,Puerto Escondido,MX,15.8500,-97.0667,82.60,77,83,3.24,broken clouds,2021-10-30 22:49:46
30,30,Bengkulu,ID,-3.8004,102.2655,76.01,90,100,5.53,overcast clouds,2021-10-30 22:49:47
34,34,Hilo,US,19.7297,-155.0900,82.13,72,40,8.05,scattered clouds,2021-10-30 22:47:31

In [7]:
clean_pref_cities_df.count()

City_ID                198
City                   198
Country                198
Lat                    198
Lng                    198
Max Temp               198
Humidity               198
Cloudiness             198
Wind Speed             198
Current Description    198
Date                   198
dtype: int64

In [8]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_pref_cities_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
4,Kapaa,US,80.58,scattered clouds,22.0752,-159.3190,
10,Cabinda,AO,77.56,light rain,-5.5500,12.2000,
11,Hua Hin,TH,77.45,overcast clouds,12.5707,99.9588,
17,Rikitea,PF,75.13,light rain,-23.1203,-134.9692,
19,Georgetown,MY,78.73,scattered clouds,5.4112,100.3354,
20,Kapoeta,SS,81.82,overcast clouds,4.7717,33.5903,
25,Soyo,AO,77.54,overcast clouds,-6.1349,12.3689,
29,Puerto Escondido,MX,82.60,broken clouds,15.8500,-97.0667,
30,Bengkulu,ID,76.01,overcast clouds,-3.8004,102.2655,
34,Hilo,US,82.13,scattered clouds,19.7297,-155.0900,

In [9]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.

    # 6c. Get latitude and longitude from DataFrame
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]
    
    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"
    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
       hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
       print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [10]:
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
4,Kapaa,US,80.58,scattered clouds,22.0752,-159.3190,Sheraton Kauai Coconut Beach Resort
10,Cabinda,AO,77.56,light rain,-5.5500,12.2000,Hotel Maiombe
11,Hua Hin,TH,77.45,overcast clouds,12.5707,99.9588,"InterContinental Hua Hin Resort, an IHG Hotel"
17,Rikitea,PF,75.13,light rain,-23.1203,-134.9692,People ThankYou
19,Georgetown,MY,78.73,scattered clouds,5.4112,100.3354,Cititel Penang
20,Kapoeta,SS,81.82,overcast clouds,4.7717,33.5903,Eastgate Hotel
25,Soyo,AO,77.54,overcast clouds,-6.1349,12.3689,Hotel Mpampa
29,Puerto Escondido,MX,82.60,broken clouds,15.8500,-97.0667,Aldea del Bazar Hotel and Spa
30,Bengkulu,ID,76.01,overcast clouds,-3.8004,102.2655,Grage Hotel Bengkulu
34,Hilo,US,82.13,scattered clouds,19.7297,-155.0900,Hilo Hawaiian Hotel

In [11]:
# 7. Drop the rows where there is no Hotel Name.
hotel_df.count()

City                   198
Country                198
Max Temp               198
Current Description    198
Lat                    198
Lng                    198
Hotel Name             198
dtype: int64

In [12]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Weather Descripion</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]

In [13]:
# 11a. Add a marker layer for each city to the map. 
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp, 0) for temp in max_temp], dissipating=False, max_intensity=250, point_radius=4.5)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))

In [14]:
# 8a. Create the output File (CSV)
output_data_file = "Vacation_Search/WeatherPy_vacation.csv"
# 8b. Export the City_Data into a csv
hotel_df.to_csv(output_data_file, index_label="City_ID")